language: node_js
node_js:
  - "12"

dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli@9

script:
- npm run prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/glory-report
  on:
    branch: master
