name: GitHub Pages

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install deps
              uses: pnpm/action-setup@v4
              with:
                  run_install: true
                  version: 9

            - name: Create env file
              run: echo "VITE_BUNGIE_API_KEY=${{ secrets.API_KEY }}" > .env

            - name: Build
              run: pnpm build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
